name: Test source files for correctness
on:
  push:
    branches-ignore:
      - main

jobs:
  source-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check that source dirs contain only *.yaml files
        run: |
          # Behold bash power and tremble!
          shopt -s extglob
          shopt -s nullglob
          for FILENAME in {accounts,collections,jettons}/!(*.yaml); do
            [ "${FILENAME}" == 'jettons/example.yaml.template' ] && continue
            echo "Found '${FILENAME}' file but only *.yaml files are allowed here."
            exit 1
          done

      - name: Dummy run of generator to check for correct syntax
        run: python3 generator.py

      - name: Report status on success
        uses: LouisBrunner/checks-action@87e7256e004e2625f00da7b5fd8c855cb520da89 # tag: v1.5.0
        if: ${{ success() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: source-syntax-check
          conclusion: "${{ job.status }}"
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Report status on failure
        uses: LouisBrunner/checks-action@87e7256e004e2625f00da7b5fd8c855cb520da89 # tag: v1.5.0
        if: ${{ ! success() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: source-syntax-check
          conclusion: "${{ job.status }}"
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
